### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by harrelchris** [ndswecker/SnatchItCore#9]
- Create accounts
- Make a profile
    - name, email, initials
    - Require admin approval
- Require staff permission to submit records

**Comment by ndswecker** [comment]
User creates their account.
The system makes them active
The admin upgrades them to staff
Only staff can make records and view records

**Comment by ndswecker** [comment]
Staff should be able to edit a previous record if they created that record

**Comment by ndswecker** [comment]
A user dashboard for all their own records might be very useful

**Comment by harrelchris** [comment]
Closed by #11
